"""add_internal_id_to_netsuite_data

Revision ID: 41fe64feb14f
Revises: 3c9764a8682f
Create Date: 2025-11-25 21:27:54.523890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fe64feb14f'
down_revision: Union[str, None] = '3c9764a8682f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netsuite_data', sa.Column('internal_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('netsuite_data', 'internal_id')
    # ### end Alembic commands ###

